// Code generated by go run ./cmd/postra-contracts; DO NOT EDIT.
// Partial canonical /api/v1 wire contracts, not every Postra API.
// Optional and nullable fields reflect Go JSON encoding; consumers must handle null.

export type AddDraftAttachmentInput = {
  "data_base64": string
  "draft_id"?: string
  "inline"?: boolean
  "name": string
}

export type AskInput = {
  /** optional owned account */
  "account_id"?: string
  /** optional sender filter */
  "from"?: string
  /** exclude completed work/actions; does not prove a mail is unanswered */
  "incomplete_only"?: boolean
  /** auto, keyword, semantic, hybrid, work, or actions */
  "mode"?: string
  /** question to answer from your own mail and work evidence */
  "question": string
  /** optional precise keyword filter; no unrelated-mail fallback */
  "search_text"?: string
  /** inclusive sender-date lower bound, Unix seconds */
  "since"?: number
  /** IANA zone for relative dates; defaults to UTC */
  "time_zone"?: string
  /** exclusive sender-date upper bound, Unix seconds */
  "until"?: number
}

export type AskResult = {
  "analysis_type"?: string
  "created_at"?: number
  "id"?: string
  "input_hash"?: string
  "model"?: string
  "prompt_version"?: string
  "result_json"?: string
  "retrieval": {
    "bounded": boolean
    "mode": string
    "since"?: number
    "sources": null | Array<{
      "action_ids"?: null | Array<string>
      "date": number
      "from": string
      "message_id": string
      "subject": string
      "work_status"?: string
    }>
    "time_zone": string
    "until"?: number
    "warnings": null | Array<string>
  }
  "target_id"?: string
  "target_type"?: string
  "user_id"?: string
}

export type AskRetrieval = {
  "bounded": boolean
  "mode": string
  "since"?: number
  "sources": null | Array<{
    "action_ids"?: null | Array<string>
    "date": number
    "from": string
    "message_id": string
    "subject": string
    "work_status"?: string
  }>
  "time_zone": string
  "until"?: number
  "warnings": null | Array<string>
}

export type AskSource = {
  "action_ids"?: null | Array<string>
  "date": number
  "from": string
  "message_id": string
  "subject": string
  "work_status"?: string
}

export type CreateDraftInput = {
  "account_id": string
  "bcc"?: null | Array<string>
  "body"?: string
  "body_author"?: string
  "body_html"?: string
  "cc"?: null | Array<string>
  "format"?: string
  "instructions"?: string
  "intent"?: string
  "kind"?: string
  "language"?: string
  "length"?: string
  "reply_to_message_id"?: string
  "signature_id"?: string
  "smart_format"?: boolean
  "subject"?: string
  "template"?: string
  "to"?: null | Array<string>
  "tone"?: string
  "use_signature"?: null | boolean
}

export type DraftAttachment = {
  "content_id"?: string
  "hash": string
  "id": string
  "inline": boolean
  "mime_type": string
  "name": string
  "scan_detail"?: string
  "scan_status": string
  "size": number
  "storage_uri": string
}

export type DraftView = {
  "draft": {
    "account_id": string
    "created_at": number
    "current_version": number
    "id": string
    "kind": string
    "reply_to_message_id"?: string
    "status": string
    "updated_at": number
    "user_id": string
  }
  "version": {
    "attachments"?: null | Array<{
      "content_id"?: string
      "hash": string
      "id": string
      "inline": boolean
      "mime_type": string
      "name": string
      "scan_detail"?: string
      "scan_status": string
      "size": number
      "storage_uri": string
    }>
    "author": string
    "bcc"?: null | Array<{
      "email": string
      "name"?: string
    }>
    "body_html"?: string
    "body_text": string
    "cc"?: null | Array<{
      "email": string
      "name"?: string
    }>
    "created_at": number
    "draft_id": string
    "subject": string
    "to": null | Array<{
      "email": string
      "name"?: string
    }>
    "version": number
  }
}

export type EffectiveSetting = {
  "active_value"?: string
  "apply": string
  "category": string
  "default": string
  "environment"?: null | Array<string>
  "help"?: string
  "key": string
  "label": string
  "lockable": boolean
  "locked": boolean
  "options"?: null | Array<string>
  "pending_restart"?: boolean
  "registered"?: boolean
  "scope": string
  "secret": boolean
  "source": string
  "type": string
  "value": string
}

export type ErrorResponse = {
  "code": string
  "details"?: null | {
    [key: string]: unknown
  }
  "message": string
  "trace_id": string
}

export type MailSignature = {
  "account_id"?: string
  "body_html"?: string
  "body_text": string
  "company"?: string
  "created_at": number
  "department"?: string
  "display_name"?: string
  "email"?: string
  "id": string
  "logo_url"?: string
  "name": string
  "phone"?: string
  "title"?: string
  "updated_at": number
  "user_id": string
}

export type MailTemplate = {
  "description": string
  "id": string
  "name": string
}

export type RenderMailInput = {
  "account_id"?: string
  "body"?: string
  "body_html"?: string
  "format"?: string
  "intent"?: string
  "language"?: string
  "length"?: string
  "reply_to_message_id"?: string
  "signature_id"?: string
  "smart_format"?: boolean
  "template"?: string
  "tone"?: string
  "use_signature"?: null | boolean
}

export type RenderedMail = {
  "body_html"?: string
  "body_text": string
  "format": string
  "template": string
  "warnings"?: null | Array<string>
}

export type SaveMailSignatureInput = {
  "account_id"?: string
  "body"?: string
  "body_html"?: string
  "company"?: string
  "department"?: string
  "display_name"?: string
  "email"?: string
  "format"?: string
  "id"?: string
  "logo_url"?: string
  "name": string
  "phone"?: string
  "title"?: string
}

export type SendPreview = {
  "attachments"?: null | Array<{
    "content_id"?: string
    "hash": string
    "id": string
    "inline": boolean
    "mime_type": string
    "name": string
    "scan_detail"?: string
    "scan_status": string
    "size": number
    "storage_uri": string
  }>
  "bcc"?: null | Array<string>
  "body": string
  "body_html"?: string
  "cc"?: null | Array<string>
  "dlp_blocked"?: boolean
  "dlp_findings"?: null | Array<{
    "count": number
    "term"?: string
    "type": string
  }>
  "draft_id": string
  "draft_version": number
  "external_domains"?: null | Array<string>
  "from": string
  "payload_hash": string
  "recipient_count": number
  "subject": string
  "to": null | Array<string>
  "warnings"?: null | Array<string>
}

export type SettingDefinition = {
  "apply": string
  "category": string
  "default": string
  "environment"?: null | Array<string>
  "help"?: string
  "key": string
  "label": string
  "lockable": boolean
  "options"?: null | Array<string>
  "scope": string
  "secret": boolean
  "type": string
}

export type SettingsPatch = {
  "locks"?: null | {
    [key: string]: boolean
  }
  "reset"?: null | Array<string>
  "revision"?: string
  /** Write-only replacement secrets. Never returned by settings reads. */
  "secrets"?: null | {
    [key: string]: string
  }
  "values"?: null | {
    [key: string]: string
  }
}

export type SettingsView = {
  "fields": null | Array<{
    "active_value"?: string
    "apply": string
    "category": string
    "default": string
    "environment"?: null | Array<string>
    "help"?: string
    "key": string
    "label": string
    "lockable": boolean
    "locked": boolean
    "options"?: null | Array<string>
    "pending_restart"?: boolean
    "registered"?: boolean
    "scope": string
    "secret": boolean
    "source": string
    "type": string
    "value": string
  }>
  "revision": string
  "runtime"?: null | {
    [key: string]: string
  }
}

export type UpdateDraftInput = {
  "bcc"?: null | Array<string>
  "body"?: null | string
  "body_html"?: null | string
  "cc"?: null | Array<string>
  "draft_id"?: string
  "format"?: string
  "intent"?: string
  "language"?: string
  "length"?: string
  "signature_id"?: string
  "smart_format"?: boolean
  "subject"?: null | string
  "template"?: string
  "to"?: null | Array<string>
  "tone"?: string
  "use_signature"?: null | boolean
}
