// Driven by TestSPABrowser: real Go auth/API/storage, in-process fake mail + AI.
// npm dependencies are development-only and are never required on offline hosts.
const assert = require('node:assert/strict');
const {chromium, expect} = require('@playwright/test');

(async () => {
  const browser = await chromium.launch({headless: true, ...(process.env.POSTRA_CHROME ? {executablePath: process.env.POSTRA_CHROME} : {})});
  const context = await browser.newContext({viewport: {width: 1520, height: 1050}, ignoreHTTPSErrors: true}); // local httptest TLS certificate only
  const page = await context.newPage();
  const base = process.env.POSTRA_TEST_URL;
  const errors = [];
  const external = [];
  page.on('pageerror', error => errors.push(error.message));
  const clickedFixtureURLs = new Set();
  context.on('request', request => {if (!request.url().startsWith(base) && !request.url().startsWith('about:') && !request.url().startsWith('data:') && !clickedFixtureURLs.has(request.url())) external.push(request.url());});
  page.on('dialog', dialog => dialog.type() === 'beforeunload' ? dialog.accept() : dialog.dismiss());
  try {
    await page.goto(base + '/app/');
    // A genuine user with zero stored actions used to crash at cards.filter.
    // No API interception: prove the real backend's empty result and navigate
    // all empty views before the seeded administrator scenario starts.
    await page.locator('[name=login_id]').fill(process.env.POSTRA_TEST_OTHER_LOGIN);
    await page.locator('[name=password]').fill(process.env.POSTRA_TEST_OTHER_PASSWORD);
    await page.getByRole('button', {name: '계정으로 로그인', exact: true}).click();
    await page.waitForURL(/\/app\/mail/);
    const emptyActions = await page.evaluate(async () => (await fetch('/api/action-cards?limit=200')).json());
    assert.deepEqual(emptyActions.cards, [], 'real empty action collection is []');
    await page.keyboard.press('Control+k');
    await page.getByRole('option', {name: '액션 센터', exact: true}).click();
    await page.getByText('아직 등록된 액션이 없습니다', {exact:true}).waitFor();
    for (const status of ['pending','approved','done','rejected','exported','']) {
      await page.getByRole('combobox',{name:'승인·완료 상태'}).selectOption(status);
      await page.getByText(status ? '조건에 맞는 액션이 없습니다' : '아직 등록된 액션이 없습니다',{exact:true}).waitFor();
    }
    for (const button of await page.getByLabel('액션 기한 분류').getByRole('button').all()) await button.click();
    await page.keyboard.press('j'); await page.keyboard.press('k');
    await page.goto(base+'/app/mail?q=no-such-empty-fixture-term');
    await page.getByText('검색 결과가 없습니다',{exact:true}).waitFor();
    await page.keyboard.press('j'); await page.keyboard.press('k');
    await page.keyboard.press('Control+k');
    await page.getByRole('option', {name:'액션 센터',exact:true}).click();
    await page.getByText('아직 등록된 액션이 없습니다',{exact:true}).waitFor();
    assert.deepEqual(errors, [], 'empty action and search routes must not produce pageerror');
    await page.getByRole('button',{name:'로그아웃',exact:true}).click();
    await page.waitForURL(url=>url.searchParams.get('sso')==='signed_out');
    await page.locator('[name=login_id]').fill(process.env.POSTRA_TEST_LOGIN);
    await page.locator('[name=password]').fill(process.env.POSTRA_TEST_PASSWORD);
    await page.getByRole('button', {name: '계정으로 로그인', exact: true}).click();
    await page.waitForURL(/\/app\/mail/);
    await page.getByRole('heading', {name: '받은메일', exact: true}).waitFor();
    await page.getByRole('button').filter({hasText: '프로젝트 킥오프 일정 공유'}).click();
    await page.getByRole('heading', {name: '프로젝트 킥오프 일정 공유'}).waitFor();
    await page.getByRole('heading', {name: 'AI Insight'}).waitFor();
    const receivedFrame = page.frameLocator('iframe[title="메일 본문"]');
    await expect(receivedFrame.getByRole('link',{name:'HTTP 안내',exact:true})).toHaveAttribute('target','_blank');
    assert.equal(await page.locator('iframe[title="메일 본문"]').getAttribute('sandbox'),'allow-popups allow-popups-to-escape-sandbox');
    assert.equal(await receivedFrame.locator('script,form,a[href^="javascript:"]').count(),0);
    assert.equal(await receivedFrame.locator('img[src]').count(),0,'remote images remain blocked while safe links work');
    const parentURL=page.url();
    async function openLink(locator,url) {
      clickedFixtureURLs.add(url);
      const popupPromise=page.waitForEvent('popup'); await locator.click(); const popup=await popupPromise;
      popup.on('pageerror',error=>errors.push(error.message));
      await popup.waitForURL(url); await expect(popup).toHaveTitle('LINK_OPENED');
      assert.equal(await popup.evaluate(()=>window.opener),null,'clicked link cannot access the mail workspace');
      assert.equal(await popup.evaluate(()=>document.referrer),'','clicked link has no referrer');
      await popup.close();
    }
    await openLink(receivedFrame.getByRole('link',{name:'HTTP 안내',exact:true}),process.env.POSTRA_TEST_LINK_HTTP);
    await openLink(receivedFrame.getByRole('link',{name:'HTTPS 안내',exact:true}),process.env.POSTRA_TEST_LINK_HTTPS);
    assert.equal(page.url(),parentURL,'mail links must never replace the workspace');
    await expect(receivedFrame.getByRole('link',{name:'메일 문의',exact:true})).toHaveAttribute('href','mailto:help@corp.local?subject=Hello');
    await expect(receivedFrame.getByRole('link',{name:'메일 문의',exact:true})).toHaveAttribute('target','_blank');
    await page.goto(base+'/app/messages/msg_spa_important');
    await openLink(page.locator('.mail-body-text').getByRole('link',{name:process.env.POSTRA_TEST_LINK_HTTP,exact:true}),process.env.POSTRA_TEST_LINK_HTTP);
    await openLink(page.locator('.mail-body-text').getByRole('link',{name:process.env.POSTRA_TEST_LINK_HTTPS,exact:true}),process.env.POSTRA_TEST_LINK_HTTPS);
    await expect(page.locator('.mail-body-text').getByRole('link',{name:'help@corp.local'})).toHaveAttribute('href','mailto:help@corp.local');
    await page.goto(parentURL);
    await page.getByRole('heading', {name: 'AI Insight'}).waitFor();
    await page.getByRole('button', {name: '요약하기', exact: true}).click();
    await expect(page.locator('.ai-panel')).toContainText('회의 자료 검토');
    assert.doesNotMatch(await page.locator('body').innerText(), new RegExp(process.env.POSTRA_TEST_PRIVATE_SUBJECT));
    const privateStatus = await page.evaluate(async id => (await fetch('/api/messages/' + id)).status, process.env.POSTRA_TEST_OTHER_MESSAGE_ID);
    assert.equal(privateStatus, 404, 'admin still cannot read another user mailbox');
    const noCSRF = await page.evaluate(async () => (await fetch('/api/drafts', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'})).status);
    assert.equal(noCSRF, 403, 'cookie writes require CSRF');
    assert.doesNotMatch(await page.evaluate(() => document.cookie), /postra_session=/, 'session must be HttpOnly');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/inbox-light.png', fullPage: true});
    await page.getByRole('button', {name: '어두운 테마', exact: true}).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/inbox-dark.png', fullPage: true});
    await page.getByRole('button', {name: '밝은 테마', exact: true}).click();
    // Follow-up workflow uses real authenticated APIs, never AI or SMTP.
    await page.getByRole('button', {name: '나중에 다시 보기', exact: true}).click();
    await page.getByRole('combobox', {name: '다시 볼 시각', exact: true}).selectOption('custom');
    await page.getByLabel('직접 지정 날짜·시각', {exact: true}).fill('2050-01-02T09:00');
    await page.getByRole('button', {name: '다시 보기 예약', exact: true}).click();
    await expect(page.getByRole('dialog', {name: '메일을 나중에 다시 보기'})).toHaveCount(0);
    const reminder = await page.evaluate(async id => (await (await fetch('/api/messages/' + encodeURIComponent(id) + '?body=false')).json()).message.snoozed_until, process.env.POSTRA_TEST_MESSAGE_ID);
    assert.ok(reminder > Date.now()/1000, 'custom reminder is saved by the real API');
    await page.getByRole('button', {name: '다시 보기 변경', exact: true}).click();
    await page.getByRole('button', {name: '예약 해제', exact: true}).click();
    await expect(page.getByRole('button', {name: '나중에 다시 보기', exact: true})).toBeVisible();
    await page.getByRole('link', {name: '이 메일에서 액션 만들기', exact: true}).click();
    await expect(page.getByLabel('액션 제목', {exact: true})).toHaveValue('프로젝트 킥오프 일정 공유');
    await page.getByRole('button', {name: '다른 메일 선택', exact: true}).click();
    await expect(page.getByRole('region', {name: '액션 원본 메일 선택'})).not.toContainText(process.env.POSTRA_TEST_PRIVATE_SUBJECT);
    await page.getByRole('button', {name: '프로젝트 킥오프 일정 공유 · 김민수 선택', exact: true}).click();
    await page.setViewportSize({width: 390, height: 844});
    await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile action form has no horizontal overflow');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/action-create-mobile.png', fullPage: true, animations: 'disabled'});
    await page.setViewportSize({width: 1520, height: 1050});
    await page.getByLabel('액션 제목', {exact: true}).fill('브라우저 후속 업무');
    await page.getByLabel('액션 담당자', {exact: true}).fill('브라우저 담당');
    await page.getByRole('button', {name: '액션 저장', exact: true}).click();
    await expect(page.getByRole('region', {name: '수동 액션 만들기'})).toHaveCount(0);
    await expect(page.getByRole('heading', {name: '브라우저 후속 업무', exact: true})).toBeVisible();
    await page.getByLabel('액션 검색', {exact: true}).fill('브라우저 담당');
    await expect(page.locator('.action-item')).toHaveCount(1);
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/actions-desktop.png', fullPage: true, animations: 'disabled'});
    await page.setViewportSize({width: 390, height: 844});
    await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile action center has no horizontal overflow');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/actions-mobile.png', fullPage: true, animations: 'disabled'});
    await page.setViewportSize({width: 1520, height: 1050});
    await page.getByRole('button', {name: '필터 초기화', exact: true}).click();
    await page.keyboard.press('Control+k');
    await page.getByRole('option', {name: '액션 센터', exact: true}).click();
    await page.getByRole('heading', {name: '액션 센터', exact: true}).waitFor();
    await expect(page.locator('body')).toContainText('회의 자료 검토');
    await page.getByRole('button', {name: '승인', exact: true}).first().click();
    await expect(page.locator('.action-item').first()).toContainText('승인됨');
    await page.goto(base + '/app/team?message=' + process.env.POSTRA_TEST_MESSAGE_ID);
    await page.getByRole('heading', {name: '처리 관리', exact: true}).waitFor();
    await page.locator('.work-detail select').selectOption('in_progress');
    await page.getByLabel('내부 메모', {exact: true}).fill('브라우저 테스트에서 자료 검토를 시작했습니다.');
    await page.getByRole('button', {name: '메모 추가', exact: true}).click();
    await expect(page.locator('.notes-list')).toContainText('브라우저 테스트에서');
    await page.getByLabel('처리 기한', {exact: false}).fill('2050-01-02T12:00');
    await page.getByRole('button', {name: '기한 저장 (빈 값은 해제)', exact: true}).click();
    await expect(page.getByRole('group', {name: '업무 기한 필터'}).getByRole('button', {name: /예정/})).toContainText('1');
    await page.getByRole('group', {name: '업무 기한 필터'}).getByRole('button', {name: /예정/}).click();
    await page.getByRole('combobox', {name: '업무 정렬', exact: true}).selectOption('deadline');
    await expect(page.getByRole('region', {name: '업무 상태 보드'})).toContainText('프로젝트 킥오프 일정 공유');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/work-desktop.png', fullPage: true, animations: 'disabled'});
    await page.setViewportSize({width: 390, height: 844});
    await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile work board has no horizontal overflow');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/work-mobile.png', fullPage: true, animations: 'disabled'});
    await page.setViewportSize({width: 1520, height: 1050});
    await page.goto(base + '/app/accounts');
    await page.getByRole('heading', {name: /메일 계정/}).first().waitFor();
    await expect(page.locator('body')).toContainText(process.env.POSTRA_TEST_EMAIL);
    await page.goto(base + '/app/ask');
    await page.getByRole('textbox', {name: 'AI에게 질문'}).fill('회의 자료에 대해 회신할 내용은?');
    await page.getByRole('button', {name: '질문하기', exact: true}).click();
    await expect(page.locator('.ai-result')).toContainText('공유된 회의 자료를 검토');
    await page.goto(base + '/app/digest');
    await page.getByRole('button', {name: '브리핑 생성', exact: true}).click();
    await expect(page.locator('.ai-result')).toContainText('프로젝트 회의 준비');
    await page.goto(base + '/app/compose');
    await page.getByRole('textbox', {name: '받는 사람', exact: true}).fill('team@corp.local');
    await page.getByRole('textbox', {name: '메일 제목', exact: true}).fill('React에서 작성한 HTML 업무 메일');
    await page.getByRole('combobox', {name: '본문 작성 방식', exact: true}).selectOption('html');
    const editor = page.getByRole('textbox', {name: '메일 본문 서식 편집기', exact: true});
    await editor.fill('안녕하세요. 자료 검토를 완료했습니다.\n자세한 내용은 아래를 확인해 주세요.');
    await editor.press('Control+a');
    await page.getByRole('button', {name: '굵게', exact: true}).click();
    await page.getByRole('combobox', {name: '메일 템플릿', exact: true}).selectOption('notice');
    await page.getByRole('button', {name: '서식 적용', exact: true}).click();
    await expect(editor).toContainText('자료 검토를 완료');
    await page.getByRole('button', {name: '초안 저장', exact: true}).click();
    await page.waitForURL(/\/app\/drafts\//);
    await expect(page.locator('.compose-page')).toContainText('저장됨');
    await page.reload();
    await expect(editor).toContainText('자료 검토를 완료');
    await page.getByRole('button', {name: '미리보기 · 발송', exact: true}).click();
    await page.getByRole('heading', {name: '발송 전 최종 확인'}).waitFor();
    const preview = page.frameLocator('iframe[title="서식 메일 미리보기"]');
    await expect(preview.locator('body')).toContainText('자료 검토를 완료');
    assert.equal(await page.locator('iframe[title="서식 메일 미리보기"]').getAttribute('sandbox'), '');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/compose-preview.png', fullPage: true});
    await page.getByRole('button', {name: '내용 확인 · 승인', exact: true}).click();
    await page.getByRole('button', {name: '승인한 메일 발송', exact: true}).click();
    await page.getByRole('heading', {name: '메일을 발송했습니다', exact: true}).waitFor();
    await page.getByRole('link', {name: '발송 기록', exact: true}).click();
    await expect(page.locator('.outbound-item')).toContainText('React에서 작성한 HTML 업무 메일');
    await expect(page.locator('.outbound-item')).toContainText('발송 완료');
    await page.goto(base + '/app/mail');
    await page.setViewportSize({width: 390, height: 844});
    await page.getByRole('heading', {name: '받은메일', exact: true}).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile has no horizontal overflow');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/inbox-mobile.png', fullPage: true});
    // The cookie jar is shared across tabs: switching identity elsewhere must
    // replace both the principal and all mailbox caches in the original tab.
    const otherTab = await page.context().newPage();
    otherTab.on('pageerror', error => errors.push(error.message));
    await otherTab.goto(base + '/app/');
    await otherTab.getByRole('button', {name: '로그아웃', exact: true}).click();
    await otherTab.waitForURL(url => url.searchParams.get('sso') === 'signed_out');
    await otherTab.locator('[name=login_id]').fill(process.env.POSTRA_TEST_OTHER_LOGIN);
    await otherTab.locator('[name=password]').fill(process.env.POSTRA_TEST_OTHER_PASSWORD);
    await otherTab.getByRole('button', {name: '계정으로 로그인', exact: true}).click();
    await otherTab.waitForURL(/\/app\/mail/);
    await expect(otherTab.locator('.mail-list')).toContainText(process.env.POSTRA_TEST_PRIVATE_SUBJECT);
    await expect(page.locator('.mail-list')).toContainText(process.env.POSTRA_TEST_PRIVATE_SUBJECT);
    await expect(page.locator('body')).not.toContainText('프로젝트 킥오프 일정 공유');
    await expect(page.getByRole('link', {name: '관리자 콘솔'})).toHaveCount(0);
    await otherTab.close();
    await page.getByRole('button', {name: '메뉴 열기'}).click();
    await page.getByRole('button', {name: '로그아웃', exact: true}).click();
    await page.waitForURL(url => url.searchParams.get('sso') === 'signed_out');
    await page.getByRole('button', {name: '계정으로 로그인'}).waitFor();
    await expect(page.locator('body')).not.toContainText('프로젝트 킥오프 일정 공유');
    assert.deepEqual(errors, [], 'no browser runtime errors');
    assert.deepEqual(external, [], 'offline runtime must not request external resources');
    console.log('PASS: real login/session/CSRF/privacy/cross-tab identity isolation, inbox/AI, dark/mobile/command, action/team, accounts/Q&A/digest, rich save/approval/send/logout; no external runtime requests');
  } catch (error) {
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/failure.png', fullPage: true});
    console.error('Visible errors:', await page.getByRole('alert').allTextContents());
    throw error;
  } finally {await browser.close();}
})().catch(error => {console.error(error); process.exitCode = 1;});
