// Driven by TestSPABrowser: real Go auth/API/storage, in-process fake mail + AI.
// npm dependencies are development-only and are never required on offline hosts.
const assert = require('node:assert/strict');
const {chromium, expect} = require('@playwright/test');

(async () => {
  const browser = await chromium.launch({headless: true, ...(process.env.POSTRA_CHROME ? {executablePath: process.env.POSTRA_CHROME} : {})});
  const context = await browser.newContext({viewport: {width: 1520, height: 1050}});
  const page = await context.newPage();
  const base = process.env.POSTRA_TEST_URL;
  const errors = [];
  const external = [];
  page.on('pageerror', error => errors.push(error.message));
  context.on('request', request => {if (!request.url().startsWith(base) && !request.url().startsWith('about:') && !request.url().startsWith('data:')) external.push(request.url());});
  page.on('dialog', dialog => dialog.type() === 'beforeunload' ? dialog.accept() : dialog.dismiss());
  try {
    await page.goto(base + '/app/');
    await page.getByRole('link', {name: '계정으로 로그인'}).click();
    await page.locator('[name=login_id]').fill(process.env.POSTRA_TEST_LOGIN);
    await page.locator('[name=password]').fill(process.env.POSTRA_TEST_PASSWORD);
    await page.getByRole('button', {name: '로그인', exact: true}).click();
    await page.waitForURL(/\/app\/mail/);
    await page.getByRole('heading', {name: '받은메일', exact: true}).waitFor();
    await page.getByRole('button').filter({hasText: '프로젝트 킥오프 일정 공유'}).click();
    await page.getByRole('heading', {name: '프로젝트 킥오프 일정 공유'}).waitFor();
    await page.getByRole('heading', {name: 'AI Insight'}).waitFor();
    await page.getByRole('button', {name: '요약하기', exact: true}).click();
    await expect(page.locator('.ai-panel')).toContainText('회의 자료 검토');
    assert.doesNotMatch(await page.locator('body').innerText(), new RegExp(process.env.POSTRA_TEST_PRIVATE_SUBJECT));
    const privateStatus = await page.evaluate(async id => (await fetch('/api/messages/' + id)).status, process.env.POSTRA_TEST_OTHER_MESSAGE_ID);
    assert.equal(privateStatus, 404, 'admin still cannot read another user mailbox');
    const noCSRF = await page.evaluate(async () => (await fetch('/api/drafts', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'})).status);
    assert.equal(noCSRF, 403, 'cookie writes require CSRF');
    assert.doesNotMatch(await page.evaluate(() => document.cookie), /postra_session=/, 'session must be HttpOnly');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/inbox-light.png', fullPage: true});
    await page.getByRole('button', {name: '어두운 테마', exact: true}).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/inbox-dark.png', fullPage: true});
    await page.getByRole('button', {name: '밝은 테마', exact: true}).click();
    await page.keyboard.press('Control+k');
    await page.getByRole('option', {name: '액션 센터', exact: true}).click();
    await page.getByRole('heading', {name: '액션 센터', exact: true}).waitFor();
    await expect(page.locator('body')).toContainText('회의 자료 검토');
    await page.getByRole('button', {name: '승인', exact: true}).first().click();
    await expect(page.locator('.action-item').first()).toContainText('승인됨');
    await page.goto(base + '/app/team?message=' + process.env.POSTRA_TEST_MESSAGE_ID);
    await page.getByRole('heading', {name: '처리 관리', exact: true}).waitFor();
    await page.locator('.work-detail select').selectOption('pending');
    await page.getByLabel('내부 메모', {exact: true}).fill('브라우저 테스트에서 자료 검토를 시작했습니다.');
    await page.getByRole('button', {name: '메모 추가', exact: true}).click();
    await expect(page.locator('.notes-list')).toContainText('브라우저 테스트에서');
    await page.goto(base + '/app/accounts');
    await page.getByRole('heading', {name: /메일 계정/}).first().waitFor();
    await expect(page.locator('body')).toContainText(process.env.POSTRA_TEST_EMAIL);
    await page.goto(base + '/app/ask');
    await page.getByRole('textbox', {name: 'AI에게 질문'}).fill('회의 자료에 대해 회신할 내용은?');
    await page.getByRole('button', {name: '질문하기', exact: true}).click();
    await expect(page.locator('.ai-result')).toContainText('공유된 회의 자료를 검토');
    await page.goto(base + '/app/digest');
    await page.getByRole('button', {name: '브리핑 생성', exact: true}).click();
    await expect(page.locator('.ai-result')).toContainText('프로젝트 회의 준비');
    await page.goto(base + '/app/compose');
    await page.getByRole('textbox', {name: '받는 사람', exact: true}).fill('team@corp.local');
    await page.getByRole('textbox', {name: '메일 제목', exact: true}).fill('React에서 작성한 HTML 업무 메일');
    const editor = page.getByRole('textbox', {name: '메일 본문 서식 편집기', exact: true});
    await editor.fill('안녕하세요. 자료 검토를 완료했습니다.\n자세한 내용은 아래를 확인해 주세요.');
    await editor.press('Control+a');
    await page.getByRole('button', {name: '굵게', exact: true}).click();
    await page.getByRole('button', {name: '공지 헤더', exact: true}).click();
    await expect(editor).toContainText('안내드립니다');
    await page.getByRole('button', {name: '초안 저장', exact: true}).click();
    await page.waitForURL(/\/app\/drafts\//);
    await expect(page.locator('.compose-page')).toContainText('저장됨');
    await page.reload();
    await expect(editor).toContainText('자료 검토를 완료');
    await page.getByRole('button', {name: '미리보기 · 발송', exact: true}).click();
    await page.getByRole('heading', {name: '발송 전 최종 확인'}).waitFor();
    const preview = page.frameLocator('iframe[title="서식 메일 미리보기"]');
    await expect(preview.locator('body')).toContainText('자료 검토를 완료');
    assert.equal(await page.locator('iframe[title="서식 메일 미리보기"]').getAttribute('sandbox'), '');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/compose-preview.png', fullPage: true});
    await page.getByRole('button', {name: '내용 확인 · 승인', exact: true}).click();
    await page.getByRole('button', {name: '승인한 메일 발송', exact: true}).click();
    await page.getByRole('heading', {name: '메일을 발송했습니다', exact: true}).waitFor();
    await page.getByRole('link', {name: '발송 기록', exact: true}).click();
    await expect(page.locator('.outbound-item')).toContainText('React에서 작성한 HTML 업무 메일');
    await expect(page.locator('.outbound-item')).toContainText('발송 완료');
    await page.goto(base + '/app/mail');
    await page.setViewportSize({width: 390, height: 844});
    await page.getByRole('heading', {name: '받은메일', exact: true}).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile has no horizontal overflow');
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/inbox-mobile.png', fullPage: true});
    // The cookie jar is shared across tabs: switching identity elsewhere must
    // replace both the principal and all mailbox caches in the original tab.
    const otherTab = await page.context().newPage();
    otherTab.on('pageerror', error => errors.push(error.message));
    await otherTab.goto(base + '/app/');
    await otherTab.getByRole('button', {name: '로그아웃', exact: true}).click();
    await otherTab.getByRole('link', {name: '계정으로 로그인'}).click();
    await otherTab.locator('[name=login_id]').fill(process.env.POSTRA_TEST_OTHER_LOGIN);
    await otherTab.locator('[name=password]').fill(process.env.POSTRA_TEST_OTHER_PASSWORD);
    await otherTab.getByRole('button', {name: '로그인', exact: true}).click();
    await otherTab.waitForURL(/\/app\/mail/);
    await expect(otherTab.locator('.mail-list')).toContainText(process.env.POSTRA_TEST_PRIVATE_SUBJECT);
    await expect(page.locator('.mail-list')).toContainText(process.env.POSTRA_TEST_PRIVATE_SUBJECT);
    await expect(page.locator('body')).not.toContainText('프로젝트 킥오프 일정 공유');
    await expect(page.getByRole('link', {name: '관리자 콘솔'})).toHaveCount(0);
    await otherTab.close();
    await page.getByRole('button', {name: '메뉴 열기'}).click();
    await page.getByRole('button', {name: '로그아웃', exact: true}).click();
    await page.getByRole('link', {name: '계정으로 로그인'}).waitFor();
    await expect(page.locator('body')).not.toContainText('프로젝트 킥오프 일정 공유');
    assert.deepEqual(errors, [], 'no browser runtime errors');
    assert.deepEqual(external, [], 'offline runtime must not request external resources');
    console.log('PASS: real login/session/CSRF/privacy/cross-tab identity isolation, inbox/AI, dark/mobile/command, action/team, accounts/Q&A/digest, rich save/approval/send/logout; no external runtime requests');
  } catch (error) {
    if (process.env.POSTRA_SPA_SCREENSHOT_DIR) await page.screenshot({path: process.env.POSTRA_SPA_SCREENSHOT_DIR + '/failure.png', fullPage: true});
    console.error('Visible errors:', await page.getByRole('alert').allTextContents());
    throw error;
  } finally {await browser.close();}
})().catch(error => {console.error(error); process.exitCode = 1;});
