package contracts

import (
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
)

func typeScript(schemas map[string]*jsonschema.Schema) ([]byte, error) {
	var out strings.Builder
	out.WriteString("// Code generated by go run ./cmd/postra-contracts; DO NOT EDIT.\n// Partial canonical /api/v1 wire contracts, not every Postra API.\n// Optional and nullable fields reflect Go JSON encoding; consumers must handle null.\n\n")
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		typ, err := tsType(schemas[name], 0)
		if err != nil {
			return nil, fmt.Errorf("TypeScript %s: %w", name, err)
		}
		fmt.Fprintf(&out, "export type %s = %s\n\n", name, typ)
	}
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}
func tsType(schema *jsonschema.Schema, indent int) (string, error) {
	if schema == nil {
		return "unknown", nil
	}
	if schema.Ref != "" || len(schema.OneOf)+len(schema.AllOf)+len(schema.AnyOf) > 0 {
		return "", fmt.Errorf("unsupported schema composition; extend generator explicitly")
	}
	types := schema.Types
	if schema.Type != "" {
		types = []string{schema.Type}
	}
	if len(types) == 0 {
		return "unknown", nil
	}
	result := []string{}
	for _, typ := range types {
		switch typ {
		case "null", "string", "boolean":
			result = append(result, typ)
		case "integer", "number":
			result = append(result, "number")
		case "array":
			items, err := tsType(schema.Items, indent)
			if err != nil {
				return "", err
			}
			result = append(result, "Array<"+items+">")
		case "object":
			var object strings.Builder
			object.WriteString("{\n")
			keys := make([]string, 0, len(schema.Properties))
			for key := range schema.Properties {
				keys = append(keys, key)
			}
			slices.Sort(keys)
			for _, key := range keys {
				child := schema.Properties[key]
				value, err := tsType(child, indent+2)
				if err != nil {
					return "", err
				}
				if child.Description != "" {
					fmt.Fprintf(&object, "%s/** %s */\n", strings.Repeat(" ", indent+2), strings.ReplaceAll(strings.Join(strings.Fields(child.Description), " "), "*/", "* /"))
				}
				optional := "?"
				if slices.Contains(schema.Required, key) {
					optional = ""
				}
				fmt.Fprintf(&object, "%s%s%s: %s\n", strings.Repeat(" ", indent+2), strconv.Quote(key), optional, value)
			}
			if len(keys) == 0 {
				value := "unknown"
				if schema.AdditionalProperties != nil {
					if schema.AdditionalProperties.Not != nil {
						value = "never"
					} else {
						var err error
						value, err = tsType(schema.AdditionalProperties, indent+2)
						if err != nil {
							return "", err
						}
					}
				}
				fmt.Fprintf(&object, "%s[key: string]: %s\n", strings.Repeat(" ", indent+2), value)
			}
			object.WriteString(strings.Repeat(" ", indent) + "}")
			result = append(result, object.String())
		default:
			return "", fmt.Errorf("unsupported type %q", typ)
		}
	}
	return strings.Join(result, " | "), nil
}
